# Generated by Django 3.2 on 2023-05-14 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230514_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Избранное'},
        ),
    ]
