# Generated by Django 3.2 on 2023-05-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_auto_20230521_0701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amountingredient',
            options={'verbose_name': 'Ингредиент'},
        ),
        migrations.RemoveConstraint(
            model_name='amountingredient',
            name='\nrecipes_amountingredient ingredient alredy added\n',
        ),
        migrations.AddConstraint(
            model_name='amountingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredients'), name='Ингредиент уже добавлен'),
        ),
    ]
