# Generated by Django 3.2 on 2023-05-21 07:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_auto_20230521_0726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amountingredient',
            options={'verbose_name': 'Количество'},
        ),
        migrations.RemoveConstraint(
            model_name='amountingredient',
            name='Ингредиент уже добавлен',
        ),
        migrations.RemoveField(
            model_name='amountingredient',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='amountingredient',
            name='ingredient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_in_recipe', to='recipes.ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='amountingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество ингредиентов'),
        ),
        migrations.AlterField(
            model_name='amountingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes_ingredients_list', to='recipes.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients', through='recipes.AmountIngredient', to='recipes.Ingredient', verbose_name='ingredients'),
        ),
    ]
