# Generated by Django 3.2 on 2023-05-22 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_auto_20230522_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_color', regex='^#([0-9a-fA-F]{3,6})$')], verbose_name='Color'),
        ),
    ]
