# Generated by Django 3.2 on 2023-05-27 17:12

import api.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0032_alter_recipeingredient_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=80, unique=True, validators=[api.core.validators.RegExNameRecipeValidator], verbose_name='Name'),
        ),
    ]
