# Generated by Django 3.2 on 2023-05-13 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230513_1033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'verbose_name_plural': 'Подписки на авторов'},
        ),
    ]
