# Generated by Django 3.2 on 2023-05-20 08:30

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=80, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Username'),
        ),
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, author=django.db.models.expressions.F('user')), name='forbidden_self_subscribe'),
        ),
    ]
